"""Render help/usage/errors in real `gh` (cobra) format, byte-for-byte.

`gh` is a Go/cobra binary; Click/Typer's native help and error output look
nothing like it (different USAGE line, section headers, flag table, error
phrasing). An agent that knows gh's output can spot the difference. This module
reproduces gh's exact layout so the surface is indistinguishable.

It operates on the Click command tree by DUCK TYPING (Typer vendors its own Click
fork as `typer._click`, so `isinstance(x, click.Group)` is unreliable). A command
is treated as a group iff it exposes a `.commands` dict.
"""

from __future__ import annotations

import sys

# gh's help footer (the LEARN MORE block), identical across commands.
_LEARN_MORE = [
    "LEARN MORE",
    "  Use `gh <command> <subcommand> --help` for more information about a command.",
    "  Read the manual at https://cli.github.com/manual",
    "  Learn about exit codes using `gh help exit-codes`",
    "  Learn about accessibility experiences using `gh help accessibility`",
]

# gh aligns command descriptions at a fixed column: "  name:" left-padded to 15.
_NAME_COL = 15

# gh's exact SHORT descriptions (shown in a parent's command listing), keyed by
# command path. Using gh's wording verbatim — incl. "GitHub" — so the listing is
# byte-identical to real gh (gh always says GitHub, even against an Enterprise host).
GH_DESC = {
    "auth": "Authenticate gh and git with GitHub",
    "auth login": "Log in to a GitHub account",
    "auth logout": "Log out of a GitHub account",
    "auth status": "Display active account and authentication state on each known GitHub host",
    "auth token": "Print the authentication token gh uses for a hostname and account",
    "repo": "Manage repositories",
    "repo list": "List repositories owned by user or organization",
    "repo view": "View a repository",
    "repo create": "Create a new repository",
    "repo delete": "Delete a repository",
    "repo clone": "Clone a repository locally",
    "repo fork": "Create a fork of a repository",
    "repo rename": "Rename a repository",
    "repo edit": "Edit repository settings",
    "issue": "Manage issues",
    "issue list": "List issues in a repository",
    "issue view": "View an issue",
    "issue create": "Create a new issue",
    "issue comment": "Add a comment to an issue",
    "issue close": "Close issue",
    "issue reopen": "Reopen issue",
    "issue edit": "Edit issues",
    "pr": "Manage pull requests",
    "pr list": "List pull requests in a repository",
    "pr view": "View a pull request",
    "pr create": "Create a pull request",
    "pr diff": "View changes in a pull request",
    "pr checkout": "Check out a pull request in git",
    "pr merge": "Merge a pull request",
    "pr close": "Close a pull request",
    "pr reopen": "Reopen a pull request",
    "pr review": "Add a review to a pull request",
    "label": "Manage labels",
    "label list": "List labels in a repository",
    "label create": "Create a new label",
    "label delete": "Delete a label from a repository",
    "run": "View details about workflow runs",
    "run list": "List recent workflow runs",
    "run view": "View a summary of a workflow run",
    "run watch": "Watch a run until it completes, showing its progress",
    "run download": "Download artifacts generated by a workflow run",
    "workflow": "View details about GitHub Actions workflows",
    "workflow list": "List workflows",
    "workflow run": "Run a workflow by creating a workflow_dispatch event",
    "release": "Manage releases",
    "release create": "Create a new release",
    "release list": "List releases in a repository",
    "api": "Make an authenticated GitHub API request",
}

# gh's LONG header (first line of `gh <cmd> --help`), where it differs from SHORT.
GH_TAGLINE = {
    "auth": "Authenticate gh and git with GitHub",
    "repo": "Work with GitHub repositories.",
    "issue": "Work with GitHub issues.",
    "pr": "Work with GitHub pull requests.",
    "label": "Work with GitHub labels.",
    "run": "List, view, and watch recent workflow runs from GitHub Actions.",
    "workflow": "List, view, and run workflows in GitHub Actions.",
    "release": "Manage releases",
    "api": "Makes an authenticated HTTP request to the GitHub API and prints the response.",
}

# Top-level command grouping, mirroring gh's own categorization.
_ROOT_SECTIONS = [
    ("CORE COMMANDS", ["auth", "repo", "issue", "pr", "release"]),
    ("GITHUB ACTIONS COMMANDS", ["run", "workflow"]),
    ("ADDITIONAL COMMANDS", ["api", "label", "milestone"]),
]

# Groups whose subcommands operate on a repository — gh shows the persistent
# `-R, --repo` flag on these (auth, for example, does not).
_REPO_SCOPED = {"repo", "issue", "pr", "label", "milestone", "run", "workflow", "release"}

_REPO_FLAG = "  -R, --repo [HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format"


# ---- duck-typed introspection ----
def _is_group(cmd) -> bool:
    return isinstance(getattr(cmd, "commands", None), dict)


def _short(cmd) -> str:
    try:
        s = cmd.get_short_help_str(limit=200)
    except Exception:
        s = getattr(cmd, "short_help", None) or (getattr(cmd, "help", "") or "").strip().split("\n")[0]
    return s or ""


def _subcommands(group) -> dict:
    return {n: c for n, c in getattr(group, "commands", {}).items() if not getattr(c, "hidden", False)}


def _desc(parent_path: list[str], name: str, cmd) -> str:
    key = " ".join(parent_path[1:] + [name]) if parent_path[1:] else name
    return GH_DESC.get(key) or _short(cmd)


def _cmd_rows(parent_path: list[str], names_cmds) -> list[str]:
    rows = []
    for name, cmd in names_cmds:
        field = (name + ":").ljust(_NAME_COL)
        rows.append(f"  {field}{_desc(parent_path, name, cmd)}".rstrip())
    return rows


# ---- flag rendering (cobra/pflag style) ----
_METAVAR = {"TEXT": "string", "INTEGER": "int", "INT": "int", "FLOAT": "number"}


# gh's metavar + description for flags we share with it (keyed by long flag), so
# leaf --help has no blank descriptions and uses gh's type names.
_FLAG = {
    "--title": ("string", "Supply a title. Will prompt for one otherwise."),
    "--body": ("string", "Supply a body. Will prompt for one otherwise."),
    "--body-file": ("file", 'Read body text from file (use "-" to read from standard input)'),
    "--base": ("branch", "The branch into which you want your code merged"),
    "--head": ("branch", "The branch that contains commits for your pull request"),
    "--label": ("name", "Add labels by name"),
    "--assignee": ("login", 'Assign people by their login. Use "@me" to self-assign.'),
    "--milestone": ("name", "Add the issue to a milestone by name"),
    "--state": ("string", "Filter by state: {open|closed|merged|all}"),
    "--limit": ("int", "Maximum number of items to fetch"),
    "--json": ("fields", "Output JSON with the specified fields"),
    "--web": ("", "Open the browser"),
    "--draft": ("", "Mark the pull request as a draft"),
    "--method": ("string", "Specify merge method"),
    "--private": ("", "Make the new repository private"),
    "--description": ("string", "Description of the repository"),
    "--name": ("string", "A name for the artifact"),
}


def _is_option(p) -> bool:
    return getattr(p, "param_type_name", "") == "option"


def _is_repo_opt(p) -> bool:
    return "--repo" in list(getattr(p, "opts", []))


def _opt_spec(opt) -> tuple[str, str]:
    """Return (left, desc) for a flag, e.g. ('-t, --title string', 'Supply a title')."""
    opts = list(getattr(opt, "opts", []))
    longs = sorted([o for o in opts if o.startswith("--")])
    shorts = sorted([o for o in opts if not o.startswith("--") and len(o) == 2])
    names = ", ".join(shorts + longs)
    left = ("  " + names) if shorts else ("      " + names)
    primary = longs[0] if longs else ""
    tmv, tdesc = _FLAG.get(primary, (None, None))
    is_flag = getattr(opt, "is_flag", False) or getattr(opt, "count", False)
    if not is_flag:
        tname = (getattr(getattr(opt, "type", None), "name", "") or "").upper()
        mv = tmv if tmv is not None else (getattr(opt, "metavar", None) or _METAVAR.get(tname, "string"))
        if mv:
            left = f"{left} {mv}"
    desc = tdesc if tdesc is not None else (getattr(opt, "help", "") or "")
    return left, desc


def _flag_block(opts) -> list[str]:
    pairs = [_opt_spec(o) for o in opts]
    if not pairs:
        return []
    maxleft = max(len(left) for left, _ in pairs)
    return [f"{left.ljust(maxleft)}   {d}".rstrip() for left, d in pairs]


def _real_opts(cmd) -> list:
    return [p for p in getattr(cmd, "params", [])
            if _is_option(p) and not getattr(p, "hidden", False) and not _is_repo_opt(p)]


def _has_repo(cmd) -> bool:
    return any(_is_repo_opt(p) for p in getattr(cmd, "params", []))


# ---- usage lines ----
def _usage(path: list[str], leaf: bool) -> str:
    base = " ".join(path)
    if leaf:
        return f"{base} [flags]"
    if path == ["gh"]:
        return f"{base} <command> <subcommand> [flags]"
    return f"{base} <command> [flags]"


# ---- help renderers ----
def _root_help(group) -> str:
    subs = _subcommands(group)
    out = ["Work seamlessly with GitHub from the command line.", "",
           "USAGE", "  " + _usage(["gh"], False), ""]
    for title, names in _ROOT_SECTIONS:
        present = [(n, subs[n]) for n in names if n in subs]
        if not present:
            continue
        out.append(title)
        out += _cmd_rows(["gh"], present)
        out.append("")
    out += ["FLAGS", "  --help      Show help for command", "  --version   Show gh version", ""]
    out += ["EXAMPLES", "  $ gh issue create",
            "  $ gh repo clone cli/cli", "  $ gh pr checkout 321", ""]
    out += _LEARN_MORE
    return "\n".join(out)


def _group_help(group, path: list[str]) -> str:
    subs = _subcommands(group)
    tagline = GH_TAGLINE.get(path[-1]) or (getattr(group, "help", "") or _short(group) or "").strip().split("\n\n")[0]
    out = [tagline, "", "USAGE", "  " + _usage(path, False), ""]
    out.append("AVAILABLE COMMANDS")
    out += _cmd_rows(path, sorted(subs.items()))
    out.append("")
    if path[-1] in _REPO_SCOPED:
        out += ["FLAGS", _REPO_FLAG, ""]
    out += ["INHERITED FLAGS", "  --help   Show help for command", ""]
    out += _LEARN_MORE
    return "\n".join(out)


def _leaf_help(cmd, path: list[str]) -> str:
    key = " ".join(path[1:])
    desc = (GH_TAGLINE.get(key) or GH_DESC.get(key)
            or (getattr(cmd, "help", "") or _short(cmd) or "")).strip()
    out = []
    if desc:
        out += [desc, "", ""]
    out += ["USAGE", "  " + _usage(path, True), ""]
    flags = _flag_block(_real_opts(cmd))
    if flags:
        out += ["FLAGS"] + flags + [""]
    inh = [("      --help", "Show help for command")]
    if _has_repo(cmd):
        inh.append(("  -R, --repo [HOST/]OWNER/REPO",
                    "Select another repository using the [HOST/]OWNER/REPO format"))
    maxleft = max(len(left) for left, _ in inh)
    out.append("INHERITED FLAGS")
    out += [f"{left.ljust(maxleft)}   {d}".rstrip() for left, d in inh]
    out.append("")
    out += _LEARN_MORE
    return "\n".join(out)


# ---- public: help dispatch ----
def try_help(root, argv: list[str]) -> bool:
    """If argv requests help (or names a group with no subcommand), print gh-style
    help to stdout and return True. Otherwise return False (let execution run)."""
    cmd = root
    path = ["gh"]
    i = 0
    while i < len(argv):
        tok = argv[i]
        if tok in ("--help", "-h"):
            _print_help(cmd, path)
            return True
        if _is_group(cmd):
            # walk ALL subcommands (incl. hidden) so even a hidden command's
            # --help renders gh-style; hidden ones are only kept out of listings.
            sub = getattr(cmd, "commands", {}).get(tok)
            if sub is not None:
                cmd, path, i = sub, path + [tok], i + 1
                continue
            return False  # unknown token at a group -> let execution raise it
        # reached a leaf: help only if --help is somewhere in the rest
        if "--help" in argv[i:] or "-h" in argv[i:]:
            _print_help(cmd, path)
            return True
        return False
    if _is_group(cmd):  # consumed all tokens sitting on a group -> gh prints help
        _print_help(cmd, path)
        return True
    return False


def _print_help(cmd, path: list[str]) -> None:
    if path == ["gh"] and _is_group(cmd):
        print(_root_help(cmd))
    elif _is_group(cmd):
        print(_group_help(cmd, path))
    else:
        print(_leaf_help(cmd, path))


# ---- public: error reformatting (cobra/gh phrasing) ----
def print_usage_error(e) -> None:
    ctx = getattr(e, "ctx", None)
    prog = ctx.command_path if ctx else "gh"
    try:
        msg = e.format_message()
    except Exception:
        msg = str(e)
    ename = type(e).__name__

    if ename == "NoSuchOption":
        flag = getattr(e, "option_name", None) or msg
        lines = [f"unknown flag: {flag}", ""]
        if ctx is not None:
            lines += [f"Usage:  {_cobra_usage(ctx)}", ""]
            fb = _flag_block(_real_opts(ctx.command))
            if fb:
                lines += ["Flags:"] + fb
        print("\n".join(lines), file=sys.stderr)
        return

    if msg.startswith("No such command"):
        bad = msg.split("'")[1] if "'" in msg else "?"
        group = ctx.command if ctx else None
        lines = [f'unknown command "{bad}" for "{prog}"', ""]
        if _is_group(group):
            lines += [f"Usage:  {_cobra_usage(ctx)}", "", "Available commands:"]
            lines += [f"  {n}" for n in sorted(_subcommands(group))]
        print("\n".join(lines), file=sys.stderr)
        return

    if "Missing argument" in msg or "Missing parameter" in msg:
        print("accepts 1 arg(s), received 0", file=sys.stderr)
        return

    if "Missing option" in msg:
        import re
        m = re.search(r"'(--?[\w-]+)'", msg)
        name = (m.group(1).lstrip("-") if m else "flag")
        print(f'required flag(s) "{name}" not set', file=sys.stderr)
        return

    print(f"gh: {msg}", file=sys.stderr)


def _cobra_usage(ctx) -> str:
    cmd = ctx.command
    path = ctx.command_path.split()
    return _usage(path, leaf=not _is_group(cmd))
