FROM aws-clone-service:local AS aws-tools

FROM python:3.10-slim

RUN useradd --create-home --shell /bin/sh agent
COPY --from=aws-tools /usr/local/bin/aws /usr/local/bin/awslocal /usr/local/bin/
COPY --from=aws-tools /opt/awscli /opt/awscli

ENV PYTHONPATH=/opt/awscli \
    AWS_ENDPOINT_URL=http://aws:4566 \
    AWS_ACCESS_KEY_ID=test \
    AWS_SECRET_ACCESS_KEY=test \
    AWS_DEFAULT_REGION=us-east-1

USER agent
WORKDIR /home/agent
CMD ["sleep", "infinity"]
